language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
  - php: 7.0 # Does not work until https://github.com/sebastianbergmann/phpunit/issues/2754 is resolved

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  # code coverage currently does not seem to be supported on travis php 7 or hhvm
  - vendor/bin/coveralls --verbose
